### ISSUE TITLE
How Can I set the values of K0 K1 K2 K3 K4

### ISSUE THREAD

**Issue by Haobo-Liu** [Dtananaev/CarlaFSD#5]
Thanks to your wonderful work! could you tell me the meanings of K0,K1,K2,K3,K4? And wheter K0 is always equal to value 1.0 or not?
Thanks again.

**Comment by Dtananaev** [comment]
Hi, 
        k0: radial distortion first coefficient
        k1: radial distortion second coefficient
        k2: tangential distortion (decentering distortion) first coefficient
        k3: tangential distortion (decentering distortion) second coefficient
        k4: radial distortion third coefficient
The difference between radial and tangential distortion explained here: https://medium.com/@d.d.tananaev/unleashing-the-power-of-fish-eye-cameras-in-carla-simulator-abb7ab5bc147

For **real camera** you want to simulate, you first need to do calibration to get the values of the coefficients K0,K1,K2,K3,K4. The calibration process if interest explained here: https://youtu.be/-9He7Nu3u8s?si=SJCzBndLRTL4Qvt6

If you don't have any distortions with this coefficients simply make all of them zero by default.

**Comment by Haobo-Liu** [comment]
Thanks a lot

**Comment by Haobo-Liu** [comment]
Hello,How can I get the intrinsic matrix values of the fisheye camera? I appreciate it a lot.
